import { CostDelta, ResourceCost, ModifiedResourceCost } from '../pricing/types';

/**
 * Format cost delta for GitHub Action PR comments with trend indicators.
 */
export class GitHubActionReporter {
  /**
   * Generate a formatted markdown report for GitHub PR comments.
   */
  generateReport(
    costDelta: CostDelta,
    baseCost?: number,
    targetCost?: number,
  ): string {
    const lines: string[] = [];

    lines.push('## 💰 CDK Cost Analysis');
    lines.push('');

    // Cost impact summary
    lines.push(this.generateCostSummary(costDelta, baseCost, targetCost));
    lines.push('');

    // Resource changes
    if (costDelta.addedCosts.length > 0) {
      lines.push(this.formatAddedResources(costDelta.addedCosts, costDelta.currency));
      lines.push('');
    }

    if (costDelta.modifiedCosts.length > 0) {
      lines.push(this.formatModifiedResources(costDelta.modifiedCosts, costDelta.currency));
      lines.push('');
    }

    if (costDelta.removedCosts.length > 0) {
      lines.push(this.formatRemovedResources(costDelta.removedCosts, costDelta.currency));
      lines.push('');
    }

    if (
      costDelta.addedCosts.length === 0 &&
      costDelta.removedCosts.length === 0 &&
      costDelta.modifiedCosts.length === 0
    ) {
      lines.push('No resource changes detected.');
      lines.push('');
    }

    // Attribution footer
    lines.push('---');
    lines.push('*Generated by [cdk-cost-analyzer](https://github.com/buildinginthecloud/cdk-cost-analyzer)*');

    return lines.join('\n');
  }

  /**
   * Generate cost impact summary with percentage change.
   */
  private generateCostSummary(
    costDelta: CostDelta,
    baseCost?: number,
    targetCost?: number,
  ): string {
    const lines: string[] = [];

    const trendIndicator = this.getTrendIndicator(costDelta.totalDelta);
    const deltaFormatted = this.formatDelta(costDelta.totalDelta, costDelta.currency);

    lines.push(`**Monthly Cost Impact:** ${trendIndicator} ${deltaFormatted}`);

    // Add percentage change if we have base/target costs
    if (baseCost !== undefined && targetCost !== undefined && baseCost > 0) {
      const percentageChange = ((targetCost - baseCost) / baseCost) * 100;
      const percentFormatted = this.formatPercentage(percentageChange);
      lines.push(`**Percentage Change:** ${percentFormatted}`);
    }

    // Add base/target cost breakdown if available
    if (baseCost !== undefined && targetCost !== undefined) {
      lines.push('');
      lines.push('| Metric | Value |');
      lines.push('|--------|-------|');
      lines.push(`| Base Monthly Cost | ${this.formatCurrency(baseCost, costDelta.currency)} |`);
      lines.push(`| Target Monthly Cost | ${this.formatCurrency(targetCost, costDelta.currency)} |`);
      lines.push(`| Cost Delta | ${deltaFormatted} |`);
    }

    return lines.join('\n');
  }

  /**
   * Format added resources table.
   */
  private formatAddedResources(resources: ResourceCost[], currency: string): string {
    const lines: string[] = [];

    lines.push('### ➕ Added Resources');
    lines.push('');
    lines.push('| Logical ID | Type | Monthly Cost |');
    lines.push('|------------|------|--------------|');

    const sorted = [...resources].sort(
      (a, b) => b.monthlyCost.amount - a.monthlyCost.amount,
    );

    for (const resource of sorted) {
      lines.push(
        `| ${resource.logicalId} | \`${resource.type}\` | ${this.formatCurrency(resource.monthlyCost.amount, currency)} |`,
      );
    }

    const total = resources.reduce((sum, r) => sum + r.monthlyCost.amount, 0);
    lines.push(`| **Total Added** | | **${this.formatCurrency(total, currency)}** |`);

    return lines.join('\n');
  }

  /**
   * Format modified resources table.
   */
  private formatModifiedResources(resources: ModifiedResourceCost[], currency: string): string {
    const lines: string[] = [];

    lines.push('### 🔄 Modified Resources');
    lines.push('');
    lines.push('| Logical ID | Type | Old Cost | New Cost | Delta |');
    lines.push('|------------|------|----------|----------|-------|');

    const sorted = [...resources].sort(
      (a, b) => Math.abs(b.costDelta) - Math.abs(a.costDelta),
    );

    for (const resource of sorted) {
      const trendIndicator = this.getTrendIndicator(resource.costDelta);
      lines.push(
        `| ${resource.logicalId} | \`${resource.type}\` | ` +
        `${this.formatCurrency(resource.oldMonthlyCost.amount, currency)} | ` +
        `${this.formatCurrency(resource.newMonthlyCost.amount, currency)} | ` +
        `${trendIndicator} ${this.formatDelta(resource.costDelta, currency)} |`,
      );
    }

    const totalDelta = resources.reduce((sum, r) => sum + r.costDelta, 0);
    const totalTrend = this.getTrendIndicator(totalDelta);
    lines.push(`| **Total Modified** | | | | **${totalTrend} ${this.formatDelta(totalDelta, currency)}** |`);

    return lines.join('\n');
  }

  /**
   * Format removed resources table.
   */
  private formatRemovedResources(resources: ResourceCost[], currency: string): string {
    const lines: string[] = [];

    lines.push('### ➖ Removed Resources');
    lines.push('');
    lines.push('| Logical ID | Type | Monthly Cost |');
    lines.push('|------------|------|--------------|');

    const sorted = [...resources].sort(
      (a, b) => b.monthlyCost.amount - a.monthlyCost.amount,
    );

    for (const resource of sorted) {
      lines.push(
        `| ${resource.logicalId} | \`${resource.type}\` | ${this.formatCurrency(resource.monthlyCost.amount, currency)} |`,
      );
    }

    const total = resources.reduce((sum, r) => sum + r.monthlyCost.amount, 0);
    lines.push(`| **Total Removed** | | **-${this.formatCurrency(total, currency)}** |`);

    return lines.join('\n');
  }

  /**
   * Get trend indicator emoji based on cost delta.
   */
  private getTrendIndicator(delta: number): string {
    if (delta > 0) {
      return '↗️';
    } else if (delta < 0) {
      return '↘️';
    }
    return '➡️';
  }

  /**
   * Format currency value.
   */
  private formatCurrency(amount: number, currency: string): string {
    const symbol = currency === 'USD' ? '$' : currency;
    return `${symbol}${amount.toFixed(2)}`;
  }

  /**
   * Format cost delta with sign.
   */
  private formatDelta(amount: number, currency: string): string {
    const sign = amount > 0 ? '+' : amount < 0 ? '' : '';
    const formatted = this.formatCurrency(Math.abs(amount), currency);
    if (amount === 0) {
      return formatted;
    }
    return amount < 0 ? `-${formatted}` : `+${formatted}`;
  }

  /**
   * Format percentage with sign.
   */
  private formatPercentage(percentage: number): string {
    const sign = percentage > 0 ? '+' : '';
    return `${sign}${percentage.toFixed(1)}%`;
  }
}
